# Math hierarchy structure
MATH_TOPICS = {
    # Core Pure Mathematics
    'Algebra': [
        'Elementary algebra',
        'Linear algebra',
        'Abstract algebra',
        'Universal algebra',
        'Algebraic geometry',
        'Arithmetic geometry',
        'Commutative algebra',
        'Noncommutative algebra',
        'Homological algebra',
        'K-theory',
        'Lattice theory',
        'Group theory',
        'Finite group theory',
        'Representation theory',
        'Lie theory',
        'Ring theory',
        'Module theory',
        'Field theory',
        'Galois theory',
        'Category theory',
        'Topos theory',
        'Algebraic combinatorics',
        'Algebraic number theory',
        'Algebraic topology',
        'Geometric algebra',
        'Clifford algebra',
        'Boolean algebra',
        'Heyting algebra'
    ],
    
    'Analysis': [
        'Real analysis',
        'Complex analysis',
        'Functional analysis',
        'Operator theory',
        'Spectral theory',
        'Nonstandard analysis',
        'Constructive analysis',
        'Harmonic analysis',
        'Fourier analysis',
        'Wavelet analysis',
        'Time-frequency analysis',
        'p-adic analysis',
        'Differential equations',
        'Ordinary differential equations',
        'Partial differential equations',
        'Integral equations',
        'Calculus of variations',
        'Geometric analysis',
        'Nonlinear analysis',
        'Numerical analysis',
        'Stochastic analysis',
        'Measure theory',
        'Ergodic theory',
        'Potential theory',
        'Approximation theory',
        'Functional equations'
    ],
    
    'Geometry and Topology': [
        'Euclidean geometry',
        'Non-Euclidean geometry',
        'Absolute geometry',
        'Affine geometry',
        'Projective geometry',
        'Synthetic geometry',
        'Analytic geometry',
        'Algebraic geometry',
        'Arithmetic geometry',
        'Diophantine geometry',
        'Differential geometry',
        'Riemannian geometry',
        'Symplectic geometry',
        'Contact geometry',
        'Complex geometry',
        'Discrete geometry',
        'Computational geometry',
        'Convex geometry',
        'Integral geometry',
        'Incidence geometry',
        'Finite geometry',
        'Tropical geometry',
        'Topology',
        'General topology',
        'Algebraic topology',
        'Geometric topology',
        'Differential topology',
        'Low-dimensional topology',
        'Knot theory',
        'Homotopy theory',
        'Homology theory',
        'Cohomology theory',
        'Sheaf theory',
        'Fiber bundles',
        'Characteristic classes',
        'Geometric group theory',
        'Teichmüller theory'
    ],
    
    'Number Theory': [
        'Elementary number theory',
        'Analytic number theory',
        'Algebraic number theory',
        'Geometric number theory',
        'Probabilistic number theory',
        'Computational number theory',
        'Transcendental number theory',
        'Diophantine approximation',
        'Diophantine equations',
        'Additive number theory',
        'Combinatorial number theory',
        'Modular forms',
        'Automorphic forms',
        'L-functions',
        'Zeta functions',
        'Iwasawa theory',
        'Arithmetic dynamics',
        'p-adic numbers',
        'p-adic analysis',
        'Valuation theory',
        'Class field theory',
        'Langlands program',
        'Elliptic curves',
        'Abelian varieties',
        'Modular curves',
        'Arithmetic algebraic geometry'
    ],
    
    'Discrete Mathematics': [
        'Combinatorics',
        'Enumerative combinatorics',
        'Algebraic combinatorics',
        'Extremal combinatorics',
        'Probabilistic combinatorics',
        'Topological combinatorics',
        'Graph theory',
        'Extremal graph theory',
        'Algebraic graph theory',
        'Topological graph theory',
        'Random graphs',
        'Hypergraphs',
        'Matroid theory',
        'Order theory',
        'Lattice theory',
        'Boolean algebra',
        'Ramsey theory',
        'Design theory',
        'Finite geometry',
        'Coding theory',
        'Cryptography',
        'Discrete geometry',
        'Polyhedral combinatorics',
        'Computational combinatorics'
    ],
    
    'Mathematical Logic': [
        'Set theory',
        'Descriptive set theory',
        'Inner model theory',
        'Large cardinal theory',
        'Forcing',
        'Determinacy',
        'Model theory',
        'Stable theory',
        'O-minimality',
        'Proof theory',
        'Reverse mathematics',
        'Ordinal analysis',
        'Type theory',
        'Homotopy type theory',
        'Recursion theory',
        'Computability theory',
        'Algorithmic randomness',
        'Descriptive complexity',
        'Constructive mathematics',
        'Intuitionistic logic',
        'Modal logic',
        'Mathematical fuzzy logic',
        'Non-classical logic',
        'Higher-order logic'
    ],
    
    # Applied Mathematics
    'Probability and Statistics': [
        'Probability theory',
        'Measure-theoretic probability',
        'Stochastic processes',
        'Markov processes',
        'Martingale theory',
        'Ergodic theory',
        'Random matrix theory',
        'Extreme value theory',
        'Large deviations theory',
        'Statistical mechanics',
        'Perplexity theory',
        'Information geometry',
        'Mathematical statistics',
        'Bayesian statistics',
        'Frequentist statistics',
        'Nonparametric statistics',
        'Semiparametric statistics',
        'Robust statistics',
        'Multivariate statistics',
        'Time series analysis',
        'Spatial statistics',
        'Stochastic geometry',
        'Statistical learning theory',
        'Survival analysis',
        'Design of experiments'
    ],
    
    'Computational Mathematics': [
        'Numerical analysis',
        'Numerical linear algebra',
        'Numerical PDEs',
        'Finite element method',
        'Spectral methods',
        'Monte Carlo methods',
        'Computational number theory',
        'Computational geometry',
        'Computational topology',
        'Computational group theory',
        'Computational statistics',
        'Symbolic computation',
        'Computer algebra',
        'Exact arithmetic',
        'Interval arithmetic',
        'Arbitrary-precision arithmetic',
        'Numerical verification',
        'Verified computation',
        'Algorithmic mathematics',
        'Computational complexity theory',
        'Quantum computing theory',
        'High-performance computing',
        'Scientific computing',
        'Mathematical software'
    ],
    
    'Mathematical Physics': [
        'Classical mechanics',
        'Quantum mechanics',
        'Quantum field theory',
        'Conformal field theory',
        'String theory',
        'M-theory',
        'Statistical mechanics',
        'Thermodynamics',
        'Electromagnetism',
        'General relativity',
        'Special relativity',
        'Gauge theory',
        'Yang-Mills theory',
        'Chern-Simons theory',
        'Twistor theory',
        'Loop quantum gravity',
        'Supersymmetry',
        'Integrable systems',
        'Soliton theory',
        'Renormalization group',
        'Condensed matter physics',
        'Plasma physics',
        'Fluid dynamics',
        'Continuum mechanics',
        'Elasticity theory',
        'Fracture mechanics',
        'Acoustics',
        'Optics',
        'Mathematical cosmology'
    ],
    
    'Optimization and Control': [
        'Linear programming',
        'Integer programming',
        'Quadratic programming',
        'Nonlinear programming',
        'Convex optimization',
        'Combinatorial optimization',
        'Stochastic optimization',
        'Robust optimization',
        'Multiobjective optimization',
        'Dynamic programming',
        'Optimal control',
        'Stochastic control',
        'Robust control',
        'Game theory',
        'Cooperative game theory',
        'Non-cooperative game theory',
        'Evolutionary game theory',
        'Mechanism design',
        'Auction theory',
        'Matching theory',
        'Network theory',
        'Queueing theory',
        'Scheduling theory',
        'Inventory theory',
        'Operations research',
        'Decision theory',
        'Risk theory',
        'Portfolio theory'
    ],
    
    # Interdisciplinary Fields
    'Financial Mathematics': [
        'Mathematical finance',
        'Financial economics',
        'Stochastic calculus',
        'Black-Scholes theory',
        'Arbitrage pricing theory',
        'Portfolio optimization',
        'Risk measures',
        'Credit risk modeling',
        'Market microstructure',
        'High-frequency trading',
        'Actuarial science',
        'Insurance mathematics',
        'Pension mathematics',
        'Financial engineering',
        'Computational finance',
        'Energy derivatives',
        'Weather derivatives',
        'Algorithmic trading'
    ],
    
    'Data Science Mathematics': [
        'Machine learning theory',
        'Statistical learning theory',
        'Computational learning theory',
        'Deep learning theory',
        'Neural network theory',
        'Kernel methods',
        'Approximation theory',
        'Information theory',
        'Algorithmic information theory',
        'Kolmogorov complexity',
        'Compressed sensing',
        'Sparse approximation',
        'Dimensionality reduction',
        'Manifold learning',
        'Topological data analysis',
        'Persistent homology',
        'Network science',
        'Graph signal processing',
        'Signal processing',
        'Image processing',
        'Computer vision mathematics',
        'Natural language processing theory',
        'Recommender systems theory',
        'Anomaly detection theory'
    ],
    
    'Theoretical Computer Science': [
        'Computational complexity theory',
        'Algorithm design',
        'Data structures',
        'Graph algorithms',
        'Geometric algorithms',
        'Parallel algorithms',
        'Distributed algorithms',
        'Randomized algorithms',
        'Approximation algorithms',
        'Online algorithms',
        'Parameterized complexity',
        'Circuit complexity',
        'Proof complexity',
        'Descriptive complexity',
        'Automata theory',
        'Formal languages',
        'Computability theory',
        'Algorithmic randomness',
        'Program verification',
        'Model checking',
        'Type theory',
        'Domain theory',
        'Concurrency theory',
        'Process calculi',
        'Information theory',
        'Coding theory',
        'Cryptography',
        'Zero-knowledge proofs',
        'Secure multiparty computation',
        'Quantum computing theory'
    ],
    
    # Special Topics
    'History of Mathematics': [
        'Ancient mathematics',
        'Babylonian mathematics',
        'Egyptian mathematics',
        'Greek mathematics',
        'Chinese mathematics',
        'Indian mathematics',
        'Islamic mathematics',
        'Medieval European mathematics',
        'Renaissance mathematics',
        'Early modern mathematics',
        '19th century mathematics',
        '20th century mathematics',
        'Foundations crisis',
        'Hilbert problems',
        'Bourbaki school',
        'Women in mathematics',
        'Ethnomathematics'
    ],
    
    'Mathematics Education': [
        'Pedagogical content knowledge',
        'Didactics of mathematics',
        'Constructivist mathematics education',
        'Cognitive theories of learning',
        'Mathematics anxiety',
        'Gifted education in mathematics',
        'Special needs in mathematics',
        'Ethnomathematics education',
        'Assessment in mathematics',
        'Curriculum development',
        'History of mathematics education',
        'Comparative mathematics education',
        'Technology in mathematics education',
        'Visualization in mathematics education'
    ],
    
    'Recreational Mathematics': [
        'Mathematical puzzles',
        'Logic puzzles',
        'Number puzzles',
        'Geometric puzzles',
        'Combinatorial games',
        'Game theory games',
        'Mathematical chess problems',
        'Magic squares',
        'Mathematical card tricks',
        'Flexagons',
        'Tessellations',
        'Fractal art',
        'Algorithmic art',
        'Mathematical music theory',
        'Mathematical poetry',
        'Mathematical humor',
        'Mathematical beauty',
        'Mathematical fiction'
    ],
    
    # Emerging Fields
    'Quantum Mathematics': [
        'Quantum algebra',
        'Quantum topology',
        'Quantum probability',
        'Quantum information theory',
        'Quantum computation theory',
        'Quantum cryptography',
        'Quantum error correction',
        'Quantum complexity theory',
        'Noncommutative geometry',
        'Quantum groups',
        'Hopf algebras',
        'Braided categories',
        'Topological quantum field theory',
        'Conformal field theory',
        'Vertex operator algebras',
        'String topology'
    ],
    
    'Mathematical Biology': [
        'Theoretical ecology',
        'Population dynamics',
        'Epidemiological modeling',
        'Neuroscience mathematics',
        'Biomechanics',
        'Cardiac modeling',
        'Cancer modeling',
        'Evolutionary dynamics',
        'Game theory in biology',
        'Tissue modeling',
        'Morphogenesis',
        'Systems biology',
        'Metabolic networks',
        'Neural networks',
        'Biostatistics',
        'Bioinformatics mathematics',
        'Genomics mathematics',
        'Proteomics mathematics'
    ],
    
    'Industrial Mathematics': [
        'Operations research',
        'Supply chain mathematics',
        'Logistics mathematics',
        'Manufacturing mathematics',
        'Quality control mathematics',
        'Reliability theory',
        'Scheduling theory',
        'Inventory theory',
        'Revenue management',
        'Pricing optimization',
        'Marketing analytics',
        'Consumer choice modeling',
        'Industrial statistics',
        'Process optimization',
        'Discrete event simulation',
        'System dynamics',
        'Mathematical economics',
        'Econometrics'
    ]
}

